# Uncomment the next line to define a global platform for your project
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'OpenLive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenLive
  pod 'Alamofire', '~> 5.1'
end
